### ISSUE TITLE
MELPA support?

### ISSUE THREAD

**Issue by skybert** [fosskers/org-table-colour#2]
This is a great package. In fact, I think this should be merged to Org itself :smile: 

But in the meantime, I'd love for this to be [installable through MELPA](https://github.com/melpa/melpa/blob/master/README.md).  Any chance you could make that happen?

All the best,

-Torstein

**Comment by fosskers** [comment]
Has been for some time! https://melpa.org/#/org-table-color

Cheers

**Comment by skybert** [comment]
Excellent!

Sorry for the spam, I searched both my Emacs and melpa. Obviously, they
both conspired against me..... Or I mistyped the name.

**Comment by fosskers** [comment]
No problem! Cheers.
